name: Pa11y Testing
on:
  # push:
  workflow_dispatch:
    inputs:
      urls:
        description: URLs to test
        required: true
        type: string
        default: "https://peteinge.com/,https://peteinge.com/work"
      dir:
        description: Directory for uploading artifacts.
        required: false
        type: string
      full_dir:
        description: Directory for uploading artifacts.
        required: false
        type: string
      result_ids:
        description: Ids of report results. To be passed through
        required: false
        type: string
      results_arr:
        description: JSON string of results -> url array.
        required: false
        type: string
      callback:
        description: Callback url for reporting results.
        required: false
        type: string

env:
  DEFAULT_URLS: "https://peteinge.com/,https://peteinge.com/work"

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - run: npm ci

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PANTHEON_SSH_KEY }}
          config: ${{ secrets.SSH_CONFIG }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      # Debugger
      # - uses: hmarr/debug-action@v3

      - name: Inputs
        run: |
          echo ${{ inputs.urls }}

      # - name: Generate URLs
      #   id: urls
      #   uses: actions/github-script@v7
      #   env:
      #     inputUrls: '${{inputs.urls}}'
      #     defaultUrls: '${{env.DEFAULT_URLS}}'
      #   with:
      #     script: |
      #       let urls = "";
      #       if (process.env.inputUrls) {
      #         urls = process.env.inputUrls.split(",");
      #       }
      #       else {
      #         urls = process.env.defaultUrls.split(",");
      #       }
      #       core.setOutput('urls', urls);

      # Debugger
      - uses: hmarr/debug-action@v3

      - name: Run script
        env:
          inputUrls: '${{inputs.urls}}'
          results_arr: '${{inputs.results_arr}}'
          defaultUrls: '${{env.DEFAULT_URLS}}'
        run: node pa11y.js

      # Debugger
      # - name: debugging files
      #   run: ls -sla



      - name: Generate Callback Message
        id: callback_msg
        uses: actions/github-script@v6
        env:
          result_ids: '${{ inputs.result_ids }}'
          results_arr: '${{ inputs.results_arr }}'
          dir: "${{ inputs.dir }}"
          full_dir: "${{ inputs.full_dir }}"
        with:
          script: |
            let msg = {};
            msg.id_string = process.env.result_ids;
            msg.dir = process.env.dir;
            msg.results_arr = process.env.results_arr;
            msg.full_dir = process.env.full_dir;
            core.setOutput('callback_msg', msg);

      - name: Post Artifacts
        timeout-minutes: 15
        env:
          CONNECT_BC_API: "${{ secrets.CONNECT_BC_KEY }}"
          EXT_DIR: "${{ inputs.dir }}"
          CALLBACK: "${{ inputs.callback }}"
          RESULTS_PATH: "./pa11y"
          CALLBACK_MSG: ${{ steps.callback_msg.outputs.callback_msg }}
        run: ./.github/scripts/pa11y-push-to-connect.sh
